learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from user1  import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('user1/',include('user1.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

learning_users/user1/urls.py
from django.conf.urls import url
from django.urls import path
from user1 import views


app_name='user1'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
 ]

learning_users/user1/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/user1/forms.py
from django import forms
from django.contrib.auth.models import User
from user1.models import User,UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

learning_users/user1/views.py
from django.shortcuts import render
from user1.models import User,UserProfileInfo
from user1.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth import login,authenticate,logout
# Create your views here.
def index(request):
    return render(request,'user1/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in!!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered= False

    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'user1/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('passw')

        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                HttpResponse("You are not active!!")
        else:
            print("Wrong Credentials")
            print("Username:{} and Password:{}".format(username,password))
            return HttpResponse("Inavlid login")

    else:
        return render(request,'user1/login.html',{})

learning_users/templates/user1/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
          <li><a class="navbar-brand" href="{%url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{%url 'user1:register'%}">Register</a></li>


          {% if user.is_authenticated %}
            <li> <a class="navbar-link" href="{%url 'logout' %}">Logout</a> </li>
          {% else %}
          <li> <a class="navbar-link" href="{% url 'user1:user_login'%}">Login</a></li>
          {% endif %}

        </ul>
      </div>

    </nav>
    <div class="container">
      {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

learning_users/templates/user1/index.html
{% extends 'user1/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>This Is the home page!!!</h1>
</div>
{% endblock %}

learning_users/templates/user1/login.html
{% extends 'user1/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <form action="{% url 'user1:user_login'%}" method="post">
    {% csrf_token %}

    <label for="username">UserName</label>
    <input type="text" name="username" placeholder="Enter User Name">
    <label for="passw">Password</label>
    <input type="password" name="passw" placeholder="*******">
    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

learning_users/templates/user1/registration.html
{% extends 'user1/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank YouFor registering!!</h1>
  {% else %}
    <h2>Fill Out The Form::</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" class="button" name="" value="Register">
    </form>



  {% endif %}
</div>
{% endblock %}